# Generated by Django 4.2.6 on 2023-10-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
