# Generated by Django 4.2.6 on 2023-10-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='recorded_file',
            field=models.FileField(default=None, upload_to='audio_files'),
        ),
        migrations.AlterModelTable(
            name='record',
            table='Record',
        ),
    ]
