# Generated by Django 4.2.6 on 2023-10-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_record_recorded_file_alter_record_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='recorded_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
    ]
