# Generated by Django 4.2.6 on 2023-10-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_record_recorded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(default='', max_length=30),
        ),
    ]
