# Generated by Django 4.2.6 on 2023-11-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_record_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
        migrations.AddField(
            model_name='record',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='removable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='record',
            name='spkr_id',
            field=models.CharField(default='SPKR000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(default='', max_length=30),
        ),
    ]
