# Generated by Django 4.2.6 on 2023-11-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_record_first_name_remove_record_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='recorded_setence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
