# Generated by Django 4.2.6 on 2023-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_record_recorded_file_0_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='recorded_setence',
            new_name='recorded_setence_0',
        ),
        migrations.AddField(
            model_name='record',
            name='recorded_setence_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='recorded_setence_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='recorded_setence_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='recorded_setence_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='recorded_setence_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='recorded_setence_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='recorded_setence_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='recorded_setence_8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='recorded_setence_9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
