# Generated by Django 4.2.6 on 2023-12-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_recorded_setence_record_recorded_setence_0_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='recorded_setence_0',
            new_name='recorded_sentence_0',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recorded_setence_1',
            new_name='recorded_sentence_1',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recorded_setence_2',
            new_name='recorded_sentence_2',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recorded_setence_3',
            new_name='recorded_sentence_3',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recorded_setence_4',
            new_name='recorded_sentence_4',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recorded_setence_5',
            new_name='recorded_sentence_5',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recorded_setence_6',
            new_name='recorded_sentence_6',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recorded_setence_7',
            new_name='recorded_sentence_7',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recorded_setence_8',
            new_name='recorded_sentence_8',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='recorded_setence_9',
            new_name='recorded_sentence_9',
        ),
    ]
