# Generated by Django 4.2.6 on 2023-12-02 13:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_recorded_setence_0_record_recorded_sentence_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='recorded_file_0',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='recorded_file_1',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='recorded_file_2',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='recorded_file_3',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='recorded_file_4',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='recorded_file_5',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='recorded_file_6',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='recorded_file_7',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='recorded_file_8',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='recorded_file_9',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
    ]
