# Generated by Django 4.2.6 on 2023-12-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_record_recorded_file_0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spkr_id', models.CharField(default='0', max_length=10)),
                ('analyzing_spkr_id', models.CharField(default='0', max_length=10)),
                ('file_to_analyze', models.FileField(blank=True, null=True, upload_to='audio_files/analysis')),
            ],
        ),
    ]
