# Generated by Django 4.2.6 on 2023-12-12 12:28

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_analysis_file_to_analyze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='file_to_analyze',
        ),
        migrations.AddField(
            model_name='analysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_to_analyze_0',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path_analyze),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_to_analyze_1',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path_analyze),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_to_analyze_2',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path_analyze),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_to_analyze_3',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path_analyze),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_to_analyze_4',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path_analyze),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_to_analyze_5',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path_analyze),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_to_analyze_6',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path_analyze),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_to_analyze_7',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path_analyze),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_to_analyze_8',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path_analyze),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_to_analyze_9',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path_analyze),
        ),
        migrations.AddField(
            model_name='analysis',
            name='method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='record_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recorded_sentence_0',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recorded_sentence_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recorded_sentence_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recorded_sentence_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recorded_sentence_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recorded_sentence_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recorded_sentence_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recorded_sentence_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recorded_sentence_8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recorded_sentence_9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
