# Generated by Django 4.2.6 on 2023-12-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_analysis_file_to_analyze_analysis_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analysis',
            table='Analysis',
        ),
    ]
